#-------------------------------
# General Site Settings

title: Simphiwe Madi
description: Software Developer, Software tester, and a really good friend
email: simphiwe@simphiwemadi.co.za
# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About, url: '#about'}
- {name: YouTube, url: '#youtube'}
- {name: Blog, url: '#blog'}
- {name: Work, url: '#work'}
- {name: Reviews, url: '#reviews'}
- {name: Notes, url: '#notes'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'This is the portfolio of Simphiwe Madi.'
  rel-author: 'Simphiwe Madi'
  rel-publisher: 'Simphiwe Madi'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Simphiwe specialises in making things** for human people.
  Most of the things he makes are <span class="blurb-section">web applications</span>,
  but he also puts effort into crafting next-level <span class="blurb-section">videos</span>
  and <span class="blurb-section">blogs</span> about making codes happen.


skills:
- {name: Soft Skills, value: '8'}
- {name: Applications Development, value: '10'}
- {name: Quality Assurance, value: '10'}
- {name: Graphic Design, value: '5'}
- {name: DevOps, value: '7'}
- {name: UX/UI Design, value: '10'}

#-------------------------------
# Work Section

projects:
- {name: Zen Magazine, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Robot Worlds, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: BetterPicks, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Animated Music Player, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Prop, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Email Newsletter, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: The portfolio of Photoletso, folder: 'proj-7', file: 'work/proj-7.html'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'face-bronwyn.jpg',
  name: 'Bronwyn Ardè',
  title: 'Head of People',
  company: 'Saicom Voice Services',
  quote: '<p> His quick sense of humour, bright smile, and positive demeanour contributed to a welcoming and uplifting atmosphere in the workplace. He demonstrated self-pride, ambition, and a maturity beyond his years, which were evident in the way he carried himself and approached his work.</p>',
  logo: 'saicom-logo.jpg'}

- {avatar: 'face-kevin.jpg',
  name: 'Kevin Mntambo',
  company: 'WeThinkCode_',
  title: 'Photographer/Videographer, Content Club.',
  quote: '<p>Working alongside Simphiwe, I got to witness his deep passionate for art and sense of community, he was and remains a great friend/allay to the Wethinkcode_ content club.</p>',
  logo: 'logo1.png'}

- {avatar: 'face-sean.jpg',
  name: 'Siphesihle (Sean) Thomo',
  title: 'Software Developer',
  company: 'WeThinkCode_',
  quote: '<p> I am very grateful to have had the opportunity to work with such a competent
          and supportive mentor. He not only provided technical expertise and support,
          but also challenged me to step out of my comfort zone and take on more difficult tasks.</p>',
  logo: 'logo1.png'}

- {avatar: 'face-kevin.jpg',
  name: 'Kevin Mntambo',
  company: 'WeThinkCode_',
  title: 'Photographer/Videographer, Content Club.',
  quote: '<p>Working alongside Simphiwe, I got to witness his deep passionate
          for art and sense of community, he was and remains a great friend/allay
          to the WeThinkCode_ content club.</p>',
  logo: 'logo1.png'}

- {avatar: 'face-bronwyn.jpg',
  name: 'Bronwyn Ardè',
  title: 'Head of People',
  company: 'Saicom Voice Services',
  quote: '<p> His quick sense of humour, bright smile, and positive demeanour contributed to a welcoming and uplifting atmosphere in the workplace. He demonstrated self-pride, ambition, and a maturity beyond his years, which were evident in the way he carried himself and approached his work.</p>',
  logo: 'saicom-logo.jpg'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/mrbrogrammer'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/simphiwe-madi-840961168'}
- {icon: 'bandcamp', link: 'https://mrfallback.bandcamp.com/track/grey-denim'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
